services:
  - type: web
    name: heart-disease-detection-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MODEL_PATH
        value: model_path.pth
    autoDeploy: true
